import dataFactory from '@rdfjs/data-model';
import type { NamedNode } from '@rdfjs/types';

/**
 * SPARQL Syntax Vocabulary
 *
 * A vocabulary for representing the syntax of SPARQL 1.2 queries and updates
 * as RDF, in the spirit of the SPIN SPARQL syntax but modeled directly on the
 * SPARQL 1.2 grammar (https://www.w3.org/TR/sparql12-query/#sparqlGrammar).
 *
 * The ontology document is shipped with this package at vocab/sparql-syntax.ttl.
 */
export const SPARQL_SYNTAX_NS = 'https://w3id.org/sparql-syntax#';

const ns = (localName: string): NamedNode => dataFactory.namedNode(SPARQL_SYNTAX_NS + localName);

/**
 * Named nodes for all terms of the SPARQL syntax vocabulary, keyed by local name.
 */
export const sparql = {
    // Query forms
    Query: ns('Query'),
    SelectQuery: ns('SelectQuery'),
    ConstructQuery: ns('ConstructQuery'),
    DescribeQuery: ns('DescribeQuery'),
    AskQuery: ns('AskQuery'),
    SubSelect: ns('SubSelect'),

    // Update operations
    Update: ns('Update'),
    Load: ns('Load'),
    Clear: ns('Clear'),
    Drop: ns('Drop'),
    Create: ns('Create'),
    Add: ns('Add'),
    Move: ns('Move'),
    Copy: ns('Copy'),
    InsertData: ns('InsertData'),
    DeleteData: ns('DeleteData'),
    DeleteWhere: ns('DeleteWhere'),
    Modify: ns('Modify'),

    // Terms
    Variable: ns('Variable'),
    BlankNode: ns('BlankNode'),
    TripleTerm: ns('TripleTerm'),

    // Graph pattern elements
    TriplePattern: ns('TriplePattern'),
    Group: ns('Group'),
    Optional: ns('Optional'),
    Union: ns('Union'),
    Minus: ns('Minus'),
    Graph: ns('Graph'),
    Service: ns('Service'),
    Filter: ns('Filter'),
    Bind: ns('Bind'),
    Values: ns('Values'),
    Exists: ns('Exists'),
    NotExists: ns('NotExists'),

    // Property paths
    SeqPath: ns('SeqPath'),
    AltPath: ns('AltPath'),
    InversePath: ns('InversePath'),
    ZeroOrMorePath: ns('ZeroOrMorePath'),
    OneOrMorePath: ns('OneOrMorePath'),
    ZeroOrOnePath: ns('ZeroOrOnePath'),
    NegatedPath: ns('NegatedPath'),

    // Expressions
    Expression: ns('Expression'),
    Or: ns('Or'),
    And: ns('And'),
    Eq: ns('Eq'),
    Neq: ns('Neq'),
    Lt: ns('Lt'),
    Gt: ns('Gt'),
    Leq: ns('Leq'),
    Geq: ns('Geq'),
    In: ns('In'),
    NotIn: ns('NotIn'),
    Addition: ns('Addition'),
    Subtraction: ns('Subtraction'),
    Multiplication: ns('Multiplication'),
    Division: ns('Division'),
    UnaryNot: ns('UnaryNot'),
    UnaryPlus: ns('UnaryPlus'),
    UnaryMinus: ns('UnaryMinus'),
    FunctionCall: ns('FunctionCall'),
    BuiltInCall: ns('BuiltInCall'),
    BuiltInFunction: ns('BuiltInFunction'),

    // Aggregates
    Aggregate: ns('Aggregate'),
    Count: ns('Count'),
    Sum: ns('Sum'),
    Min: ns('Min'),
    Max: ns('Max'),
    Avg: ns('Avg'),
    Sample: ns('Sample'),
    GroupConcat: ns('GroupConcat'),

    // Miscellaneous structure
    Alias: ns('Alias'),
    Asc: ns('Asc'),
    Desc: ns('Desc'),

    // Named individuals
    undef: ns('undef'),
    DefaultGraph: ns('DefaultGraph'),
    NamedGraphs: ns('NamedGraphs'),
    AllGraphs: ns('AllGraphs'),

    // Properties
    version: ns('version'),
    where: ns('where'),
    projection: ns('projection'),
    star: ns('star'),
    distinct: ns('distinct'),
    reduced: ns('reduced'),
    template: ns('template'),
    describeTargets: ns('describeTargets'),
    from: ns('from'),
    fromNamed: ns('fromNamed'),
    subject: ns('subject'),
    predicate: ns('predicate'),
    object: ns('object'),
    elements: ns('elements'),
    graph: ns('graph'),
    endpoint: ns('endpoint'),
    silent: ns('silent'),
    expression: ns('expression'),
    variable: ns('variable'),
    varName: ns('varName'),
    label: ns('label'),
    arg: ns('arg'),
    arg1: ns('arg1'),
    arg2: ns('arg2'),
    args: ns('args'),
    function: ns('function'),
    groupBy: ns('groupBy'),
    having: ns('having'),
    orderBy: ns('orderBy'),
    limit: ns('limit'),
    offset: ns('offset'),
    values: ns('values'),
    variables: ns('variables'),
    bindings: ns('bindings'),
    pathElements: ns('pathElements'),
    path: ns('path'),
    countStar: ns('countStar'),
    separator: ns('separator'),
    operations: ns('operations'),
    source: ns('source'),
    into: ns('into'),
    graphTarget: ns('graphTarget'),
    fromGraph: ns('fromGraph'),
    toGraph: ns('toGraph'),
    data: ns('data'),
    deleteTemplate: ns('deleteTemplate'),
    insertTemplate: ns('insertTemplate'),
    withGraph: ns('withGraph'),
    using: ns('using'),
    usingNamed: ns('usingNamed'),

    // Built-in function individuals
    STR: ns('STR'),
    LANG: ns('LANG'),
    LANGMATCHES: ns('LANGMATCHES'),
    LANGDIR: ns('LANGDIR'),
    DATATYPE: ns('DATATYPE'),
    IRI: ns('IRI'),
    URI: ns('URI'),
    BNODE: ns('BNODE'),
    BOUND: ns('BOUND'),
    STRLEN: ns('STRLEN'),
    UCASE: ns('UCASE'),
    LCASE: ns('LCASE'),
    ENCODE_FOR_URI: ns('ENCODE_FOR_URI'),
    CONTAINS: ns('CONTAINS'),
    STRSTARTS: ns('STRSTARTS'),
    CONCAT: ns('CONCAT'),
    STRENDS: ns('STRENDS'),
    STRBEFORE: ns('STRBEFORE'),
    STRAFTER: ns('STRAFTER'),
    STRLANG: ns('STRLANG'),
    STRLANGDIR: ns('STRLANGDIR'),
    STRDT: ns('STRDT'),
    ABS: ns('ABS'),
    CEIL: ns('CEIL'),
    FLOOR: ns('FLOOR'),
    ROUND: ns('ROUND'),
    RAND: ns('RAND'),
    YEAR: ns('YEAR'),
    MONTH: ns('MONTH'),
    DAY: ns('DAY'),
    HOURS: ns('HOURS'),
    MINUTES: ns('MINUTES'),
    SECONDS: ns('SECONDS'),
    TIMEZONE: ns('TIMEZONE'),
    TZ: ns('TZ'),
    NOW: ns('NOW'),
    MD5: ns('MD5'),
    SHA1: ns('SHA1'),
    SHA256: ns('SHA256'),
    SHA384: ns('SHA384'),
    SHA512: ns('SHA512'),
    sameTerm: ns('sameTerm'),
    isIRI: ns('isIRI'),
    isURI: ns('isURI'),
    isBLANK: ns('isBLANK'),
    isLITERAL: ns('isLITERAL'),
    isNUMERIC: ns('isNUMERIC'),
    COALESCE: ns('COALESCE'),
    IF: ns('IF'),
    UUID: ns('UUID'),
    STRUUID: ns('STRUUID'),
    isTRIPLE: ns('isTRIPLE'),
    TRIPLE: ns('TRIPLE'),
    SUBJECT: ns('SUBJECT'),
    PREDICATE: ns('PREDICATE'),
    OBJECT: ns('OBJECT'),
    hasLANG: ns('hasLANG'),
    hasLANGDIR: ns('hasLANGDIR'),
    REGEX: ns('REGEX'),
    SUBSTR: ns('SUBSTR'),
    REPLACE: ns('REPLACE'),
} as const;

/**
 * Maps the lexer token type names of SPARQL built-in function keywords to the
 * corresponding built-in function individuals of the vocabulary.
 */
export const BUILT_IN_FUNCTIONS: Record<string, NamedNode> = {
    STR: sparql.STR,
    LANG: sparql.LANG,
    LANGMATCHES: sparql.LANGMATCHES,
    LANGDIR: sparql.LANGDIR,
    DATATYPE: sparql.DATATYPE,
    IRI: sparql.IRI,
    URI: sparql.URI,
    BNODE: sparql.BNODE,
    BOUND: sparql.BOUND,
    STRLEN: sparql.STRLEN,
    UCASE: sparql.UCASE,
    LCASE: sparql.LCASE,
    ENCODE_FOR_URI: sparql.ENCODE_FOR_URI,
    CONTAINS: sparql.CONTAINS,
    STRSTARTS: sparql.STRSTARTS,
    CONCAT: sparql.CONCAT,
    STRENDS: sparql.STRENDS,
    STRBEFORE: sparql.STRBEFORE,
    STRAFTER: sparql.STRAFTER,
    STRLANG: sparql.STRLANG,
    STRLANGDIR: sparql.STRLANGDIR,
    STRDT: sparql.STRDT,
    ABS: sparql.ABS,
    CEIL: sparql.CEIL,
    FLOOR: sparql.FLOOR,
    ROUND: sparql.ROUND,
    RAND: sparql.RAND,
    YEAR: sparql.YEAR,
    MONTH: sparql.MONTH,
    DAY: sparql.DAY,
    HOURS: sparql.HOURS,
    MINUTES: sparql.MINUTES,
    SECONDS: sparql.SECONDS,
    TIMEZONE: sparql.TIMEZONE,
    TZ: sparql.TZ,
    NOW: sparql.NOW,
    MD5: sparql.MD5,
    SHA1: sparql.SHA1,
    SHA256: sparql.SHA256,
    SHA384: sparql.SHA384,
    SHA512: sparql.SHA512,
    SAMETERM: sparql.sameTerm,
    ISIRI: sparql.isIRI,
    ISURI: sparql.isURI,
    ISBLANK: sparql.isBLANK,
    ISLITERAL: sparql.isLITERAL,
    ISNUMERIC: sparql.isNUMERIC,
    COALESCE: sparql.COALESCE,
    IF: sparql.IF,
    UUID: sparql.UUID,
    STRUUID: sparql.STRUUID,
    ISTRIPLE: sparql.isTRIPLE,
    TRIPLE: sparql.TRIPLE,
    SUBJECT: sparql.SUBJECT,
    PREDICATE: sparql.PREDICATE,
    OBJECT: sparql.OBJECT,
    HASLANG: sparql.hasLANG,
    HASLANGDIR: sparql.hasLANGDIR,
    REGEX: sparql.REGEX,
    SUBSTR: sparql.SUBSTR,
    REPLACE: sparql.REPLACE,
};
